### ISSUE TITLE
Question: Is it possible to run the docker container with an enabled GPU?

### ISSUE THREAD

**Issue by thomaskrause** [OCR4all/docker_image#16]
I successfully used the docker image on a server and can preprocess and perform the recognition without any issues. For the training step, however, it seems like no GPU is used even when activated in the settings. Did I miss anything in the instructions or is it just not possible to use the GPU for training yet?

I found https://github.com/NVIDIA/nvidia-docker and successfully used this to loop through the GPUs to the existing docker image via the `--gpus all` command and checking it by running `nvidia-smi` inside the container. But the pre-packaged TensorFlow does not report any GPUs when running `tf.config.experimental.list_physical_devices('GPU')` in a Python shell since the CUDA libraries seem to be missing.

**Comment by maxnth** [comment]
You're right, sadly none of our currently available Docker images for OCR4all offer GPU support (which may understandably be a bit frustrating for certain use cases).
We plan to offer an additional Docker image with GPU support for the upcoming v0.5 of OCR4all in late October/early November (maybe earlier if I can find some time to look into it).

If you want to leverage your GPU when training a model, the easiest way at the moment would probably be to directly use [calamari](https://github.com/Calamari-OCR/calamari). calamari will work with the PAGE XML files created by OCR4all. 
Adding the trained models to your mapped `models` directory will make them show up in the OCR4all front end as well.

The following command (the paths have to be adjusted obviously) would train an 5-fold model ensemble (one the binary images) using the data from two different OCR4all projects (only training on one project would work accordingly)

```
calamari-cross-fold-train \
--files /path/to/first/ocr4all/project/processing/*.bin.png /path/to/second/ocr4all/project/processing/*.bin.png \
--dataset PAGEXML \
--n_folds 5 \
--num_threads 56 \
--best_models_dir /some/dir/models \
--display 100 \
--batch_size 5 \
--temporary_dir /some/dir/tmp \
--text_regularization spaces \
--n_augmentation 5
```

**Comment by thomaskrause** [comment]
Thanks for the answer and the workaround! I will try it out and see if this can be integrated in our workflow.
